### ISSUE TITLE
Tracking Issue for clean-up / refactoring days

### ISSUE THREAD

**Issue by grtlr** [iotaledger/bee#1024]
We are on the verge of getting rid of the `chrysalis-pt2` branch. Once this transition is complete, it's a good time to do some clean-up and refactoring. This issue acts as a tracking issue for the things that are not so nice and that we want to clean up.

Everyone can just comment with things that might require focus. From this list we can then create the individual issues.

Also, just because someone raises an issue here does not mean they are the one working on it :trollface:.

**Comment by grtlr** [comment]
* [ ] Streamline `KIND` and `FeatureFlags`
* [ ] Add missing generators to `bee-test/rand`
* [ ] Transfer functionality to plugin system
* [ ] Clean-up `bee-node` (maybe @thibault-martinez)
* [ ] Create `bee-identity` (@Alex6323 already working on this)
* [ ] Cleanup `bee-protocol`
  * [ ] Get rid of TODOs
  * [ ] Write documentation

**Comment by grtlr** [comment]
* [ ] #1070 (@thibault-martinez)
* [ ] #1116
* [ ] #1158
