### ISSUE TITLE
Compare codebase with syntactical validation rules from RFCs

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#441]

**Comment by Adam-Gleave** [comment]
## Messages

I looked through the messages RFC yesterday, and the syntactic validation rules all look to be met, except for item 5:

 > `Parents' length` must be 2.

In Bee, however, the length of `parents` is checked to be within the inclusive range `1..=8`:

```rust
//! message.rs

// Line 19
pub const MESSAGE_PARENTS_RANGE: RangeInclusive<usize> = 1..=8;

// Lines 189-191 (MessageBuilder::finish)
if !MESSAGE_PARENTS_RANGE.contains(&message.parents.len()) {
    return Err(Error::InvalidMessageLength(message_bytes.len()));
}
```

This seems to make sense alongside new changes to allow many parents for a message. Is this something that needs to be updated in the RFC instead?

### Notes
1) In Bee there are 5 payload types, all of which have a value within the range specified in item 3 in the RFC. However, the `Payloads` table in the RFC only describes three types: `Signed Transaction`, `Milestone Draft`, and `Indexation Payload`. Bee also contains the `Receipt` and `TreasuryTransaction` types. This looks like it might need to be updated in the RFC as well.
2) When looking into item 4, I found a small typo in `bee-pow/src/providers/miner.rs` –  I believe the variable `trainling_zeros` declared at line 88 should be `trailing_zeros`. Extremely minor though!

I managed to get through about half of the transactions RFC yesterday, so I'll add a separate comment for that when completed.

### Findings
 - [x] Bee enables between 1 and 8 parents for a message. The RFC specifies a maximum of 2 parents.
 - [x] Bee defines more payload types than are defined in the RFC, although all types are valid according to syntactic rules.
 - [x] Small typo!

**Comment by Adam-Gleave** [comment]
## Transactions

### Essences

Most of the validations specified in the transactions RFC relating to the transaction Essences are met, with one note:

 - As well as `SignatureLockedSingle` and `SignatureLockedDustAllowance` outputs types, Bee also defines a `TreasuryOutput`. I believe the validation item is still met though, since constructing a `RegularEssence` using a `RegularEssenceBuilder` will result in an error when it includes a `TreasuryOutput` type.

### Unlock Blocks

The following validation items are not checked by Bee:

1) > A `Signature Unlock Block` unlocking multiple inputs must only appear once (be unique) and be positioned at the same index of the first input it unlocks. All other inputs unlocked by the same `Signature Unlock` Block must have a companion `Reference Unlock` at the same index as the corresponding input which points to the origin `Signature Unlock Block`.

   I believe the commented code within `TransactionPayloadBuilder` checks to ensure that each `Signature Unlock Block` is unique, but does not check indices to ensure blocks are in the right position.

2) > `Reference Unlock Block`s must specify a previous `Unlock Block` which is not of type `Reference Unlock Block`. The reference index must therefore be < the index of the `Reference Unlock Block`.
   
   The commented code in `TransactionPayloadBuilder` does check that the reference index is < the index of the reference block, but it does not validate the type of the unlock block at the reference index, meaning that a `Reference Unlock Block` could potentially reference another `Reference Unlock Block`.

### Notes

There are quite a few validation items here that are not specifically checked by Bee on building a `TransactionPayload`, but they are enforced in other areas of the code. Is this an issue, or is this correct?

For example, the item that states all `Signature Unlock Block`s must define an `Ed25519` signature is not checked explicitly, but Bee only defines a single variant in the `SignatureUnlock` enum, so this will hold true:

```rust
pub enum SignatureUnlock {
    Ed25519(Ed25519Signature),
}
```

## Findings
 - [x] Bee defines a `TreasuryOutput` that is not defined in the RFC, even though it is not currently used. Does this need an RFC update?
 - [x] Unlock Block indices are not checked to ensure they are in the correct position
 - [x] When using `ReferenceUnlock`, the variant of the `UnlockBlock` at the given reference index is not checked to ensure it is a `SignatureUnlock`
 - [x] No check that inputs/outputs are lexicographically sorted in their serialised forms.
 - [x] Do all validation items need explicit checks on building struct instances, or is it enough to enforce these constraints in other areas of the code (as in the above example)?

**Comment by Adam-Gleave** [comment]
## Milestones

There are a couple of mismatches between the RFC and Bee's milestone message implementation:

1) Similar to the parent count in the messages RFC, the milestone RFC only references two parents:

   > `Parent1` and `Parent2` of the payload must match `Parent1` and `Parent2` of the encapsulating Message.
   
   Instead, Bee allows up to 8 parents.

2) > Public keys must be unique.
3) > The provided keys must be in lexicographical order
   
   I can't seem to find checks for these two anywhere...I might be looking in the wrong place!

## Findings
- [x] Bee allows 8 parents, where the RFC references 2
- [x] No check that all public keys are unique
- [x] Public keys are not necessarily sorted in lexicographical order

**Comment by Adam-Gleave** [comment]
## Dust Protection

Only two items in the validation list on this one, so it was pretty quick! One of these items looks to be unimplemented right now:

1) > The `Address` must be unique in the set of `SigLockedDustAllowanceOutput`s in one transaction T. However, there can be one `SigLockedSingleOutput` and one `SigLockedDustAllowanceOutputs` T.

I cannot find the above check in the code, or the commented block in `TransactionPayloadBuilder`.

## Findings
- [x] No check that all `SigLockedDustAllowanceOutput`s in a single transaction contain unique addresses.
