### ISSUE TITLE
Tracking Issue for `chrono`/`time` fixes

### ISSUE THREAD

**Issue by Adam-Gleave** [iotaledger/bee#786]
This is a tracking issue for addressing #783 and #779.

### Steps

- [ ] Remove `chrono` as a direct dependency of Bee. 
- [ ] Update any dependencies that have subdependencies on `chrono` or an effected `time` version, if these have been patched with fixes.
- [x] For dependencies that appear inactive, fork and patch them ourselves, and submit a PR to the maintainer.
- [ ] Remove the advisories CI bypass

**Comment by Adam-Gleave** [comment]
[`tracing`](https://github.com/tokio-rs/tracing/pull/1646) has merged a patch for this issue, but we are waiting on a release.

**Comment by Adam-Gleave** [comment]
Opened [this PR](https://github.com/acw/simple_asn1/pull/26) for `simple_asn1`, which is used in `jsonwebtoken`.

(This has now been merged).

**Comment by Adam-Gleave** [comment]
Opened [`this PR`](https://github.com/Keats/jsonwebtoken/pull/211) for `jsonwebtoken`, now that `simple_asn1` has had a new release, and [`tokio-console`](https://github.com/tokio-rs/console/pull/175) has merged dependency updates.

**Comment by jyhi** [comment]
Looks like a lot has been made regarding to the two security issues, but this tracking issue is not updated for a while.

**Comment by thibault-martinez** [comment]
We're just waiting for dependencies to merge the PRs we did to fix these issues.
