### ISSUE TITLE
Tracking Issue for the transition to `backstage`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/bee#852]
This is a tracking issue for the transition to [_Backstage_](https://github.com/iotaledger/backstage/tree/stable), which is IOTA's actor framework that originated in _Chronicle_ (@LouayKamel). Currently, Bee uses a custom worker system and we will have to see how these workers map to actors in the new framework.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter.

### Challanges

* @pvdrz raised the point that Bee does a considerable amount of logic in the `.stop` method of a worker, but Backstage does not offer the same functionality. In these cases, we will probably need a supervisor that takes care of this logic.
* Coming up with a good strategy to divide this refactor into logical parts, so that we can always have a working state and don't have to do everything at once.

### General

The current PR for the transition is: #855 

As a first step, I looked at all the workers that we have to convert (topological order, retrieved by logging in `debug` mode):

* [x] `bee_protocol::workers::metrics::MetricsWorker`
* [x] `bee_protocol::workers::mps::MpsWorker`
* [ ] ~~`bee_protocol::workers::peer::manager_res::PeerManagerResWorker`~~ (investigate removing this)
* [ ] ~~`bee_tangle::tangle_worker::TangleWorker`~~ (investigate removing this)
* [ ] `bee_protocol::workers::requester::message::MessageRequesterWorker`
  * split into two parts (can maybe be combined in a common supervisor again)
  * [x] `MessageRetryerActor`
  * [ ] `MessageRequesterActor`
* [ ] `bee_protocol::workers::requester::milestone::MilestoneRequesterWorker`
* [ ] `bee_ledger::workers::snapshot::worker::SnapshotWorker`
* [ ] `bee_ledger::workers::consensus::worker::ConsensusWorker`
* [ ] `bee_protocol::workers::index_updater::IndexUpdaterWorker`
* [ ] `bee_protocol::workers::solidifier::MilestoneSolidifierWorker`
* [ ] `bee_protocol::workers::propagator::PropagatorWorker`
* [ ] `bee_protocol::workers::broadcaster::BroadcasterWorker`
* [ ] `bee_protocol::workers::message::payload::indexation::IndexationPayloadWorker`
* [ ] `bee_protocol::workers::message::payload::transaction::TransactionPayloadWorker`
* [ ] `bee_protocol::workers::message::payload::milestone::MilestonePayloadWorker`
* [ ] `bee_protocol::workers::message::payload::PayloadWorker`
* [ ] `bee_protocol::workers::message::unreferenced_inserter::UnreferencedMessageInserterWorker`
* [ ] `bee_protocol::workers::message::processor::ProcessorWorker`
* [ ] `bee_protocol::workers::message::hasher::HasherWorker`
* [ ] `bee_protocol::workers::message::submitter::MessageSubmitterWorker`
* [ ] `bee_network::service::host::integrated::ServiceHost`
* [ ] `bee_network::network::host::integrated::NetworkHost`
* [ ] `bee_protocol::workers::responder::message::MessageResponderWorker`
* [ ] `bee_protocol::workers::responder::milestone::MilestoneResponderWorker`
* [ ] `bee_tangle::tip_pool_cleaner_worker::TipPoolCleanerWorker`
* [ ] `bee_node::plugins::version_checker::VersionChecker`
* [ ] `bee_node::plugins::PluginWorker<bee_node::plugins::mps::Mps>`
* [ ] `bee_node::plugins::mqtt::Mqtt`
* [x] `bee_protocol::workers::heartbeater::HeartbeaterWorker`
* [x] `bee_protocol::workers::status::StatusWorker`
* [ ] `bee_rest_api::endpoints::ApiWorker`
* [ ] `bee_protocol::workers::peer::manager::PeerManagerWorker`

### Steps

* [ ] Create a flat actor structure based on the [topological order of the workers](https://github.com/iotaledger/bee/blob/47e099851cdef0ebf2eb49f7553d2f30aebe89ac/bee-node/src/node/builder.rs#L286) and implement it in a single supervisor.
* [ ] Get rid of all `Worker` skeletons
* [ ] Better document the time intervals used in combination with `IntervalChannel` (https://github.com/iotaledger/backstage/issues/12)
* [ ] Several workers performed custom shutdown logic, but Actors in `backstage` don't have the same functionality as the supervisor takes care of cleanup. Luckily, most of these workers only deal with properly closing `Resource`s, which is something that we can do from the supervisor. The following is a (WIP) list of these workers:
  * [ ] `bee_protocol::workers::peer::manager_res::PeerManagerResWorker`
  * [ ] `bee_tangle::tangle_worker::TangleWorker`

### Resources

* [Backstage repository](https://github.com/iotaledger/backstage/tree/stable)
* [Example using `from_config`](https://github.com/iotaledger/backstage/blob/stable/backstage-core/examples/root.rs)
* [`scylla.rs`](https://github.com/iotaledger/scylla.rs/)

### Implementation history

* Old draft PR for using Backstage: #691
* PR using `backstage` inside `bee-network`: #674

**Comment by grtlr** [comment]
Another thing that we need to consider is how we handle resources. If I understand correctly, these share mutable state between workers in the current system. Would we keep them as resources, or should they be converted into actors as well?

**Comment by pvdrz** [comment]
What I've found so far is that sharing resources between `bee-node` and `backstage` is the largest issue here. I migrated `MetricsWorker` to `backstage` but now I have no way to share `NodeMetrics` back to `bee-node` because `bee-node` uses it's own `ResourceHandle`. I'll see if I can pass an `Arc<NodeMetrics>` back to `bee-node` and wrap it in a `ResourceHandle` again.

**Comment by grtlr** [comment]
Interesting! Is that only a problem during the time of transition or a general problem that we will have to deal with?￼ Can we get rid of resources all together, and switch over to Backstage's ￼directory functionality?

**Comment by pvdrz** [comment]
Is just a transition issue. I believe that the easiest way would be to keep dummy workers that register the resources under `bee-node` and then propagate them through `backstage` when we initialize its runtime. 

I'll check if it actually works or not.

EDIT: It's aliveeee

**Comment by pvdrz** [comment]
So It seems the workflow would be something like:
- Write a new `FooActor: Actor` for every `FooWorker: Worker`.
- Take all the logic inside  `FooWorker` and move it to `FooActor` except for resource registration.
- Put every resource registered by a worker as a field of the `NodeSupervisor` so we can propagate it down the supervision tree inside `NodeBuilder::finish`.
- Initialize every `FooActor` with the right `Data` by taking whatever resource we need from the `NodeSupervisor`.

I did this process for the `MetricsWorker` in this commit: https://github.com/iotaledger/bee/pull/855/commits/f0bc5dc463ddde60ae786aaf0fc0527e06770b99 and it is working (I left some comments for clarity). I'd migrate the `MpsWorker` or the `HeartbeaterWorker` next as their logic is similar. Maybe the first one is easier as it has less resources just by being higher in our list.

**Comment by grtlr** [comment]
Awesome. Using these steps, I was able to transition the `MpsWorker` in the latest commit to #855. A couple of observations:

* Maybe `MpsActor` should be a child of `MpsMetrics` in the actor hierarchy. However, I was not able to spawn it in `MpsMetrics::init`. If I read the errors correctly, the problem is that the `Channel` types are not compatible.
* I've run the node, but I feel like the events are send more often than specified in `IntervalChannel`. Particularly, `MpsActor` now spams the logs. Changing the (static) values did not seem to have an impact.

Maybe @LouayKamel can chime in on these points? Thanks!

**Comment by pvdrz** [comment]
The errors are tricky. I think what's happening is that `MetricsActor` would need to be able to receive status change events to be able to supervise `MpsMetrics`. So we would have to change the channel as you said and do the "ticking" mechanism in a different way.

**Comment by pvdrz** [comment]
Ok so `PeerManagerResWorker` is going to be tricky because its only work is to shutdown the `PeerManager` struct. Technically this should be done by a supervisor that owns the `PeerManager` resource and every actor depending on it should be under its supervision. But we are doing things flat for now. The main blocker here is that `PeerManager` is being shared between `backstage` and `bee-runtime` which means that the `PeerManagerResActor` cannot actually own the `PeerManager`. 

I'm going to figure out some temporal workaround so once every worker that requires the `PeerManager` has been migrated we can remove the workaround.

Edit: I decided it is not worth to lose time doing the workaround and just move to other worker.

**Comment by pvdrz** [comment]
Migrating `StatusWorker` had a particular issue that @grtlr already mentioned before via Discord. This worker uses the `Tangle<B>` and that means that its `Actor` implementation must be generic over `B` somehow. I could only do that by adding a `PhantomData<B>` field to `StatusActor` as shown here (https://github.com/iotaledger/bee/pull/855/commits/e2e6ebff34ecdbb16084bb2a6eb0b120e73dffe3) but maybe there is a better way. @LouayKamel what do you think?

**Comment by louaykamel** [comment]
@pvdrz Yeah I mentioned this limitation to @grtlr yesterday.
Our backstage actor trait doesn't have a secondary generic Bound.
- The best solution is to propogate this through the actor structs, which I think is convenient, as these kind of use cases the propagation is 2 levels at most. 

- Another work around is to add Bound generic to the actor trait and the runtime struct. I experimented with this solution in the early days using the [minimal](https://github.com/iotaledger/backstage/blob/882abc673cd66d647343b285dddf026cda015c1c/examples/resource_child.rs#L149) branch.


Personally I prefer the current design, as I had the same issue with selective permanode mode generic bound, but then turned out quite nicely.

What are your thoughts?

**Comment by pvdrz** [comment]
I wouldn't change anything inside `backstage` to be honest as I think adding more stuff to `Actor` would clutter it.

But at the same time I'd like to avoid making every `Actor` generic over `B: StorageBackend` in some way. The best I could think about was to sandwich a custom subtrait of `SupHandle` that includes an asociated type `Backend: StorageBackend`:

```rust
use std::marker::PhantomData;

// In backstage

trait Actor<S> where S: SupHandle<Self> {}

trait SupHandle<T: ?Sized> {}

// In bee-storage

trait StorageBackend {}

// In bee-protocol

trait SupHandleWithStorage<T: ?Sized>: SupHandle<T> {
    type Backend: StorageBackend;
}

struct MyActor;

impl<S: SupHandleWithStorage<Self>> Actor<S> for MyActor {}

struct MyHandle<S, B> {
    handle: S,
    _marker: PhantomData<(B, )>,
}

impl<T: ?Sized, S: SupHandle<T>, B: StorageBackend> SupHandle<T> for MyHandle<S, B> {
    // Just reuse `S: SupHandle<T>` impl.
}

impl<T: ?Sized, S: SupHandle<T>, B: StorageBackend> SupHandleWithStorage<T> for MyHandle<S, B> {
    type Backend = B;
}
```
In that way you can access `S::Backend` from the `Actor<S>` implementation for `MyActor`. What say you?

**Comment by louaykamel** [comment]
Hmm, I thought about creating a generic wrapper handle type and channel type that impl everything using blanket at the runtime level and then use these types when needed, I might be able to also register the pure handle type instead of wrapped as the handle resource. To enable any other actor without B/G bound to lookup for the other handle.

I will look into this

**Comment by pvdrz** [comment]
I would implement this in the `bee` codebase instead of inside `backstage` to save you extra work as this feels very bee specific.

**Comment by louaykamel** [comment]
I agree, so simply create two wrappers:
MyHandle<H, B> (as you mentioned), and also create MyChannel<C, B> wrapper, then impl the channel/builder traits and use these when required.

**Comment by pvdrz** [comment]
Yeah I could even avoid the generics and use our own `BeeSupervisor` and just use `BeeSupervisor::Handle` and `BeeSupervisor::Channel::Handle`.

**Comment by pvdrz** [comment]
this was my attempt to get it working but I wasn't successful, I couldn't create a proper ChannelBuilder: 
```diff
diff --git a/bee-node/src/node/mod.rs b/bee-node/src/node/mod.rs
index 0a3c4a53..6ed9507f 100644
--- a/bee-node/src/node/mod.rs
+++ b/bee-node/src/node/mod.rs
@@ -6,7 +6,7 @@ mod error;
 
 use bee_protocol::{
     types::metrics::NodeMetrics,
-    workers::{MetricsActor, MpsActor, RequestedMessages, StatusActor},
+    workers::{BeeSupHandle, MetricsActor, MpsActor, RequestedMessages, StatusActor},
 };
 use bee_tangle::Tangle;
 pub use builder::BeeNodeBuilder;
@@ -19,7 +19,8 @@ use bee_runtime::{event::Bus, node::Node, resource::ResourceHandle, worker::Work
 use anymap::{any::Any as AnyMapAny, Map};
 use async_trait::async_trait;
 use backstage::core::{
-    AbortableUnboundedChannel, Actor, ActorResult, EolEvent, ReportEvent, Rt, ScopeId, Service, SupHandle,
+    AbortRegistration, AbortableUnboundedChannel, AbortableUnboundedHandle, Actor, ActorResult, Channel,
+    ChannelBuilder, EolEvent, Report, ReportEvent, Route, Rt, ScopeId, Service, Shutdown, SupHandle,
 };
 use futures::{channel::oneshot, future::Future, StreamExt};
 use log::{debug, info, warn};
@@ -175,6 +176,102 @@ impl<T> ReportEvent<T> for NodeSupervisorEvent {
     }
 }
 
+struct NodeSupervisorHandle<B: StorageBackend> {
+    handle: AbortableUnboundedHandle<NodeSupervisorEvent>,
+    _marker: PhantomData<(B,)>,
+}
+
+impl<B: StorageBackend> Clone for NodeSupervisorHandle<B> {
+    fn clone(&self) -> Self {
+        Self {
+            handle: self.handle.clone(),
+            _marker: PhantomData,
+        }
+    }
+}
+
+#[async_trait]
+impl<B: StorageBackend> Shutdown for NodeSupervisorHandle<B> {
+    async fn shutdown(&self) {
+        self.handle.shutdown().await
+    }
+
+    fn scope_id(&self) -> ScopeId {
+        self.handle.scope_id()
+    }
+}
+
+#[async_trait]
+impl<B: StorageBackend, T: 'static + Send> Report<T> for NodeSupervisorHandle<B> {
+    async fn report(&self, scope_id: ScopeId, service: Service) -> Option<()>
+    where
+        T: Actor<Self>,
+        Self: SupHandle<T>,
+    {
+        self.handle
+            .send(<NodeSupervisorEvent as ReportEvent<T>>::report_event(scope_id, service))
+            .ok()
+    }
+}
+
+#[async_trait]
+impl<B: StorageBackend, T: 'static + Send> SupHandle<T> for NodeSupervisorHandle<B> {
+    type Event = NodeSupervisorEvent;
+
+    async fn eol(self, scope_id: ScopeId, service: Service, actor: T, r: ActorResult<()>) -> Option<()>
+    where
+        T: Actor<Self>,
+    {
+        self.handle
+            .send(NodeSupervisorEvent::eol_event(scope_id, service, actor, r))
+            .ok()
+    }
+}
+
+#[async_trait]
+impl<B: StorageBackend, T: 'static + Send> BeeSupHandle<T> for NodeSupervisorHandle<B> {
+    type Backend = B;
+}
+
+struct NodeSupervisorChannel<B: StorageBackend> {
+    channel: AbortableUnboundedChannel<NodeSupervisorEvent>,
+    _marker: PhantomData<(B,)>,
+}
+
+impl<B: StorageBackend> Channel for NodeSupervisorChannel<B> {
+    type Event = NodeSupervisorEvent;
+
+    type Handle = NodeSupervisorHandle<B>;
+
+    type Inbox = <AbortableUnboundedChannel<NodeSupervisorEvent> as Channel>::Inbox;
+
+    type Metric = <AbortableUnboundedChannel<NodeSupervisorEvent> as Channel>::Metric;
+
+    fn channel<T>(
+        self,
+        scope_id: ScopeId,
+    ) -> (
+        Self::Handle,
+        Self::Inbox,
+        AbortRegistration,
+        Option<Self::Metric>,
+        Option<Box<dyn Route<Self::Event>>>,
+    ) {
+        let (handle, inbox, abort_registration, metric, route) = self.channel.channel::<T>(scope_id);
+
+        (
+            NodeSupervisorHandle {
+                handle,
+                _marker: PhantomData,
+            },
+            inbox,
+            abort_registration,
+            metric,
+            route,
+        )
+    }
+}
+
 struct NodeSupervisor<B: StorageBackend> {
     bus: ResourceHandle<Bus<'static>>,
     metrics: ResourceHandle<NodeMetrics>,
@@ -182,14 +279,26 @@ struct NodeSupervisor<B: StorageBackend> {
     requested_messages: ResourceHandle<RequestedMessages>,
 }
 
-#[async_trait::async_trait]
+#[async_trait]
+impl<B: StorageBackend> ChannelBuilder<NodeSupervisorChannel<B>> for NodeSupervisor<B> {
+    async fn build_channel<S>(&mut self) -> ActorResult<NodeSupervisorChannel<B>> {
+        Ok(NodeSupervisorChannel {
+             // channel: <NodeSupervisor<B> as ChannelBuilder<AbortableUnboundedChannel<NodeSupervisorEvent>>>::build_channel(self as &mut NodeSupervisor<B>).await?,
+             channel: todo!(),
+            _marker: PhantomData,
+        })
+    }
+}
+
+
+#[async_trait]
 impl<S, B> Actor<S> for NodeSupervisor<B>
 where
     S: SupHandle<Self>,
     B: StorageBackend,
 {
     type Data = ();
-    type Channel = AbortableUnboundedChannel<NodeSupervisorEvent>;
+    type Channel = NodeSupervisorChannel<B>;
 
     async fn init(&mut self, rt: &mut Rt<Self, S>) -> ActorResult<Self::Data> {
         log::info!("Root: {}", rt.service().status());
@@ -208,7 +317,7 @@ where
         // TODO: This could maybe be done right from the metrics actor.
         rt.start(Some("mps".into()), MpsActor::default()).await?;
 
-        rt.start(Some("status".into()), StatusActor::<B>::default()).await?;
+        rt.start(Some("status".into()), StatusActor::default()).await?;
 
         Ok(())
     }
diff --git a/bee-protocol/src/workers/status.rs b/bee-protocol/src/workers/status.rs
index a26cd226..16150748 100644
--- a/bee-protocol/src/workers/status.rs
+++ b/bee-protocol/src/workers/status.rs
@@ -1,9 +1,9 @@
 // Copyright 2020-2021 IOTA Stiftung
 // SPDX-License-Identifier: Apache-2.0
 
-use crate::workers::{storage::StorageBackend, MessageRequesterWorker, RequestedMessages};
+use crate::workers::{storage::StorageBackend, BeeSupHandle, MessageRequesterWorker, RequestedMessages};
 
-use backstage::core::{Actor, ActorError, ActorResult, IntervalChannel, Rt, StreamExt, SupHandle};
+use backstage::core::{Actor, ActorError, ActorResult, IntervalChannel, Rt, StreamExt};
 use bee_ledger::workers::consensus::ConsensusWorker;
 use bee_runtime::{node::Node, resource::ResourceHandle, worker::Worker};
 use bee_tangle::{Tangle, TangleWorker};
@@ -11,24 +11,17 @@ use bee_tangle::{Tangle, TangleWorker};
 use async_trait::async_trait;
 use log::info;
 
-use std::{any::TypeId, convert::Infallible, marker::PhantomData};
+use std::{any::TypeId, convert::Infallible};
 
-pub struct StatusActor<B: StorageBackend> {
-    _marker: PhantomData<(B,)>,
-}
-
-impl<B: StorageBackend> Default for StatusActor<B> {
-    fn default() -> Self {
-        Self { _marker: PhantomData }
-    }
-}
+#[derive(Default)]
+pub struct StatusActor {}
 
 #[async_trait]
-impl<S, B: StorageBackend> Actor<S> for StatusActor<B>
+impl<S> Actor<S> for StatusActor
 where
-    S: SupHandle<Self>,
+    S: BeeSupHandle<Self>,
 {
-    type Data = (ResourceHandle<Tangle<B>>, ResourceHandle<RequestedMessages>);
+    type Data = (ResourceHandle<Tangle<S::Backend>>, ResourceHandle<RequestedMessages>);
     // FIXME: interval is passed through configuration and it is not a constant.
     type Channel = IntervalChannel<1000>;
 
@@ -38,7 +31,7 @@ where
             .ok_or_else(|| ActorError::aborted_msg("actor has no parent"))?;
 
         let tangle = rt
-            .lookup::<ResourceHandle<Tangle<B>>>(parent_id)
+            .lookup::<ResourceHandle<Tangle<S::Backend>>>(parent_id)
             .await
             .ok_or_else(|| ActorError::exit_msg("resource is not available"))?;
 
```

**Comment by louaykamel** [comment]
Alright, I pushed the requested changes, and added `Marker` wrapper, which can be used for both channel and handle.

**Comment by grtlr** [comment]
I will be splitting up the `MessageRequesterWorker` into two parts because currently it is doing two things at once:

* Requesting messages
* Retrying requested messages (done already; now `MessageRetryerActor`)

Ideally, we can recombine these two concerns under a new supervisor once we move away from the flat actor hierarchy.

**Comment by pvdrz** [comment]
I took a look at `MilestoneResponderWorker` which is the first worker that actually receives messages from the rest of the node and I am wondering how to send messages from `bee-runtime` to actors in `backstage` given that the `backstage` runtime starts after the whole `bee-runtime` is up. I supoose one option is letting the worker expose the receiver end of its channel as a resource and then pass this channel to the `backstage` runtime. However that means that we wouldn't be using the `backstage` runtime to pass messages.

The other option would be to flip everything and start the `backstage` runtime first, letting it initialize and handle all the resources and then somehow pass the receiver end of each actor to `bee-runtime` somehow. However that'd mean that we'd have to change everything we've done so far.
